### ISSUE TITLE
specifying numeric vector of starting abundance via sim_N0 within sim_abundance()

### ISSUE THREAD

**Issue by krtanaka** [PaulRegular/SimSurvey#9]
Hello, 

I am trying figure out how to specify a numeric vector of starting abundance within sim_abundance() using sim_N0. It looks like R0 and Z0 are both NULL by default within sim_N0(). How do you specify R0=1000, for example, in sim_abundance()? Apologize in advance if I'm missing something obvious.

**Comment by PaulRegular** [comment]
Good question, and sorry that this is not clear in the documentation. As you noticed, `sim_N0()` does not allow `R0` to be directly specified because, inside of `sim_abundance()`, the function was set-up to use the first recruitment value generated by the `sim_R()` closure. With this in mind, the functions can be forced to specify specific starting values, including the `R0` value, by providing a vector of recruits and starting values:

```
R_fun <- sim_R(log_mean = log(c(1000, 200, 10, 1000, 5)), 
                              log_sd = 0, random_walk = FALSE, plot = TRUE)
R_fun(years = 1:5)
N0_fun <- sim_N0(N0 = c(500, 100, 10, 5, 1), plot = TRUE)
N0_fun(R0 = 1000, ages = 1:6)

pop <- sim_abundance(ages = 1:6, years = 1:5,
                     R = R_fun, N0 = N0_fun)
pop$N
```
Hope this helps!

**Comment by krtanaka** [comment]
Thank you for the clarification!
